version: "3.8"

services:
  backend-ci:
    container_name: backend_ci_container_v2   # Changed name to backend_ci_container_v2
    build:
      context: ./backend
    ports:
      - "5000:4000" # Changed port
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend-ci:
    container_name: frontend_ci_container_v2  # Changed name to frontend_ci_container_v2
    build:
      context: ./frontend
    ports:
      - "5273:5173" # Changed port
    volumes:
      - ./frontend:/app
    depends_on:
      - backend-ci
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
